---
title: "NWM"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://ufokn.com/", align: right }
    theme: flatly
    orientation: row
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinycustomloader)

library(dataRetrieval)
library(nhdplusTools)
library(nwmHistoric)
library(tidycensus)

library(lubridate)

library(leaflet)
library(sf)
library(ggplot2)
library(dplyr)
library(dygraphs)
library(DT)
library(formattable)



source('nwm_shiny/helper.R')
```

```{r context="server"}
#Initialize Maps 
output$catchMap     <- renderLeaflet({ basemap() })
output$catchMap_2     <- renderLeaflet({ second_map() })
# output$countyMap <- renderLeaflet({ pop_map(pop) })

comid <<- reactive({
  comid <-  input$catchMap_click
})

# comid <<- reactiveValues(comid = NULL)

nwm <- reactiveValues()
# 
# current_data <- reactive({
#   req(comid)
#   nwm <- readNWMdata(comid = comid)
#   })

# pop <<- get_acs(geography = "county",
#                  variables = "B01003_001",
#                  geometry = TRUE)
#   
#   pop$area <- st_area(pop)
#   
#   pop$area <- units::set_units(pop$area, "mi^2")
#   pop <- rename(pop, population = estimate)
#   pop <- pop %>%
#     mutate(pop_density = population/area)
#   pop <- pop %>% filter(!grepl("^02", GEOID))
#   pop <- pop %>% filter(!grepl("^15", GEOID))
#   pop <<- st_transform(pop, 4326)

# get_nwm <- reactive({
#   if(is.null(comid)) {
#     NULL
#   } else {
#   comid <- isolate(comid)
#   nwm <- readNWMdata(comid = comid)
#   print("test")
#   nwm <- head(nwm, 10)
#   nwm
#   }
# })
```



NWM {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}
dateRangeInput("dateTS", label = "Date Range Input",
               start = "1993-01-01",
               end = "2018-12-31",
               format = "yyyy mm dd",
               weekstart = 1)
verbatimTextOutput("dateTSText")
verbatimTextOutput("dateTSText2")
```

### **Submit**
```{r}
shiny::actionButton("dateButton", label = "Enter", icon("search"))
```

```{r context = "server"}
  r <- reactiveValues(
    change_datewindow = 0,
    change_dateTS = 0,
    change_datewindow_auto = 0,
    change_dateTS_auto = 0,
    dateTS = c(start = "1993-01-01",
               end = "2018-12-31")
  )


  observeEvent(input$catchTS_date_window, {
    message(crayon::blue("observeEvent_input_catchTS_date_window"))
    r$change_datewindow <- r$change_datewindow + 1
    if (r$change_datewindow > r$change_datewindow_auto) {

      r$change_dateTS_auto <- r$change_dateTS_auto + 1
      r$change_datewindow_auto <- r$change_datewindow

    start <- as.Date(ymd_hms(input$catchTS_date_window[[1]]))
    stop  <- as.Date(ymd_hms(input$catchTS_date_window[[2]]))
   updateDateRangeInput(session = session,
                       inputId = "dateTS",
                       start = start,end = stop
                       )
      
    } else {
      if (r$change_datewindow >= 10) {
        r$change_datewindow_auto <- r$change_datewindow <- 0
      }
    }
  })

  observeEvent(input$dateTS, {
    message("observeEvent_input_dateTS")
    r$change_dateTS <- r$change_dateTS + 1
    if (r$change_dateTS > r$change_dateTS_auto) {
      message("event input_year update")

      r$change_datewindow_auto <- r$change_datewindow_auto + 1
      r$change_dateTS_auto <- r$change_dateTS

      r$dateTS <- input$dateTS

    } else {
      if (r$change_dateTS >= 10) {
        r$change_dateTS_auto <- r$change_dateTS <- 0
      }
    }
  })
  observeEvent(input$catchMap_click, {
    
    click <<- input$catchMap_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid <- nldi$comid
    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    
      output$catchTS <- renderDygraph({
        print("date change button")
        dygraph(ts)  %>%
          dyHighlight(highlightCircleSize = 2,
                highlightSeriesBackgroundAlpha = .3) %>%
          dyOptions(colors = c("darkcyan"),
              fillGraph = TRUE) %>%
          dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
                                         as.character(r$dateTS[2] + 1)))
      })
})

  observeEvent(input$catchMap_click, {
    
    click <<- input$catchMap_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid <- nldi$comid
    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    
      output$catchTS <- renderDygraph({
        print("date change button")
        dygraph(ts)  %>%
          dyHighlight(highlightCircleSize = 2,
                highlightSeriesBackgroundAlpha = .3) %>%
          dyOptions(colors = c("darkcyan"),
              fillGraph = TRUE) %>%
          dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
                                         as.character(r$dateTS[2] + 1)))
      })
})
  
  
# observeEvent(input$dateButton, {
#     nwm <- nwm
#     ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
# 
# 
# 
# 
#     output$catchTS <- renderDygraph({
# 
#       dygraph(ts)  %>%
#         dyHighlight(highlightCircleSize = 2,
#                 highlightSeriesBackgroundAlpha = .3) %>%
#         dyOptions(colors = c("darkcyan"),
#               fillGraph = TRUE) %>%
#         dyRangeSelector(dateWindow = c(as.character(input$dateTS[1]), as.character(input$dateTS[2])))
#     })
# 
# })

```

Row 
-----------------------------------------------------------------------
### 
```{r}
valueBoxOutput("comidBox")
```

Row 
-----------------------------------------------------------------------
### Draw
```{r}
leafletOutput("catchMap")
```

```{r context = "server"}
#  lat = 35.6643
# lng = -96.91935
# 
#  pt <- data.frame(lat, lng)
#    pt <- sf::st_as_sf(pt,
#                         coords = c("lng", "lat"),
#                         crs = 4326)
#        nldi <- findNLDI(location = pt)

# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + info panel
  observeEvent(input$catchMap_click, {
   if(!is.null(input$catchMap_click)) {
    click <<- input$catchMap_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid = nldi$comid
    print(comid)
    print("map1_click2")
    catch_df <- get_nhdplus(comid = comid, realization = "catchment")
   
    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt,
                 layerId = ~comid,) %>% 
      addPolygons( data = catch_df,
                   col = 'blue') 
      # zoom_to_catch(catch_df, comid)
    
    leafletProxy("catchMap_2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df,
                   col = 'blue')
   } 
})

# catchMap and catchMap_2 are linked while zooming
  observe({ # Observer to respond to zoom / pan of map1 and apply to map2
    coords <- input$catchMap_center
    zoom <- input$catchMap_zoom
    print(coords)
    print(zoom)
    if (!is.null(coords)) {
      leafletProxy("catchMap_2") %>%
        setView(lat = coords$lat, lng = coords$lng, zoom = zoom)
    }
})
```

Row 
-----------------------------------------------------------------------
### Time series
```{r}
dygraphOutput("catchTS")
```

### Map 2
```{r}
leafletOutput("catchMap_2")
```

```{r context = "server"}
# observeEvent(input$catchMap_click, {
#     # pt <<- NULL
#     click <<- input$catchMap_click %>%
#       data.frame() %>%
#       dplyr::select(lat,lng)
#     print(click)
#     pt <- sf::st_as_sf(click,
#                         coords = c("lng", "lat"),
#                         crs = 4326)
#     nldi <- findNLDI(location = pt)
#     #
#     comid <- nldi$comid
#     nwm <- readNWMdata(comid = comid)
#     print("nwm test")
#     ts = xts::xts(as.data.frame(nwm$flow_cms), order.by = nwm$dateTime, tz= 'UTC')
#     print("ts1")
#     output$catchTS <- renderDygraph({
#         print("map1_click")
#         make_ts4(ts)
#   })
# })
```















