---
title: "NOAA"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://water.noaa.gov/about/nwm", align: right }
    theme: cerulean
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinycustomloader)

library(dataRetrieval)
library(nhdplusTools)
library(nwmHistoric)
library(climateR)
library(USAboundaries)
library(USAboundariesData)
library(lubridate)

library(leaflet)
library(sf)
library(ggplot2)
library(dplyr)
library(dygraphs)
library(DT)
library(plotly)
library(highcharter)
# library(gt)


source('helper2.R')
```

```{r context="server"}
#Initialize Maps 
output$catchMap     <- renderLeaflet({ basemap() })
output$catchMap2     <- renderLeaflet({ second_map() })
output$catchMap3 <- renderLeaflet({ basemap() })
# output$countyMap <- renderLeaflet({ pop_map(pop) })

# comid <<- reactiveValues(comid = NULL)

comid <- reactive({
    comid <-  input$catchMap_click
    comid <-  input$catchMap2_click
    comid <-  input$catchMap3_click
})

nwm <- reactiveValues()
```



National Water Model {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}

# div(style = "height: 1000px; width: 80%; margin: 0; padding: 0; background-color: rgba(0,0,0,.4)",
#       div(style = "height: 100%; width: 100%; margin: 0; padding: 0",
#           highchartOutput("Result",  width = "100%", height = "160%")))
        #     withLoader(type = "html", loader = "loader6")
        # ))
dateRangeInput("dateTS", label = "Date Range Input",
               start = "1993-01-01",
               end = "2018-12-31",
               min = "1993-01-01",
               max = "2018-12-31",
               format = "yyyy mm dd",
               weekstart = 1)
DTOutput("summaryTable")
```

### **Submit**
```{r}
shiny::actionButton("dateButton", label = "Enter", icon("search"))
```

Row
-----------------------------------------------------------------------
### 
```{r}
valueBoxOutput("comidBox")
```

Row {data-height=700}
-----------------------------------------------------------------------

###
```{r, fig.width = 350}

leafletOutput("catchMap")
```

###
```{r, fig.width = 250}
# fig.width = 550
leafletOutput("catchMap2")
```

```{r context = "server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + info panel
  observeEvent(input$catchMap_click, {
   if(!is.null(input$catchMap_click)) {
    click <<- input$catchMap_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid <<- nldi$comid
    print(comid)
    print("map1_click")
    
    # catch_df <- get_nhdplus(comid = comid, realization = "catchment")
    bb <- nldi %>%
      st_centroid() %>%
      st_buffer(0.05)
    
    catch_df2 <- get_nhdplus(AOI = bb, realization = "catchment")
    
    catch_df <- catch_df2 %>%
      filter(featureid == comid)
    
    output$comidBox <- renderValueBox({
    valueBox(value = paste("COMID: ", comid)) })
    
    bounds <- st_bbox(pt) %>% 
      st_as_sfc() %>% 
      st_buffer(.05) %>% 
      st_bbox() %>% 
      as.vector()
    
    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt,
                 layerId = ~comid) %>% 
       addPolygons( data = catch_df,
                   fillColor = 'red',
                   col = "black",
                   weight = 2) %>% 
      flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
      # addPolygons( data = catch_df2,
      #              col = 'red') 
      # zoom_to_catch(catch_df, comid)
    
    leafletProxy("catchMap2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df,
                   fillColor = 'red',
                   col = "white",
                   weight = 2) %>%
      addPolygons( data = catch_df2,
                   fillColor = 'transparent',
                   col = "white",
                   weight = 2) %>% 
      flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
      # addPolygons( data = catch_df2,
      #              col = 'red')
    # 
    # output$summaryTable <- renderDT({
    #     make_table3(comid)
    #   })

     # summaryData <- eventReactive(input$dateButton, {
        #   make_table3(comid)
        # })
        # output$summaryTable <- renderDT({
        #       summaryData()
   } 
})

# click on map 2 will render polygon, point on map 1 and 3
observeEvent(input$catchMap2_click, {
   if(!is.null(input$catchMap2_click)) {
    click <<- input$catchMap2_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid = nldi$comid
    print(comid)
    print("map2_click")
    #
    # catch_df <- get_nhdplus(comid = comid, realization = "catchment")
    
    bb <- nldi %>% 
      st_centroid() %>% 
      st_buffer(0.05)
    # bb <- st_bbox(nldi) # current bounding box
    # # bounding box range
    # xrange <- bb$xmax - bb$xmin # range of x values
    # yrange <- bb$ymax - bb$ymin # range of y values
    # # expand bb by 60%
    # bb[1] <- bb[1] - (0.6 * xrange) # xmin - left
    # bb[3] <- bb[3] + (0.6 * xrange) # xmax - right
    # bb[2] <- bb[2] - (0.6 * yrange) # ymin - bottom
    # bb[4] <- bb[4] + (0.6 * yrange) # ymax - top
    # # make bb a sfc
    # bb <- bb %>%  # take the bounding box ...
    #     st_as_sfc()
    catch_df2 <- get_nhdplus(AOI = bb, realization = "catchment")
    catch_df <- catch_df2 %>%
      filter(featureid == comid)
    
    output$comidBox <- renderValueBox({
    valueBox(value = paste("COMID: ", comid)) })
    
    bounds <- st_bbox(pt) %>% 
      st_as_sfc() %>% 
      st_buffer(.05) %>% 
      st_bbox() %>% 
      as.vector()
    
    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt,
                 layerId = ~comid,) %>% 
      addPolygons( data = catch_df,
                   fillColor = 'red',
                   col = "black",
                   weight = 2) %>% 
      flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
      # addPolygons( data = catch_df2,
      #              col = 'blue')
      # zoom_to_catch(catch_df, comid)
    leafletProxy("catchMap2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df,
                   fillColor = 'red',
                   col = "white",
                   weight = 2) %>% 
      addPolygons( data = catch_df2,
                   fillColor = "transparent",
                   col = "white",
                   weight = 2)
   } 
})

# catchMap and catchMap2 are linked while zooming
  observe({ # Observer to respond to zoom / pan of map1 and apply to map2
    coords <- input$catchMap_center
    zoom <- input$catchMap_zoom
    print(coords)
    print(zoom)
    if (!is.null(coords)) {
      leafletProxy("catchMap2") %>%
        setView(lat = coords$lat, lng = coords$lng, zoom = zoom)
    }
})
```


Row
-----------------------------------------------------------------------

### Time series 
```{r}
dygraphOutput("catchTS")
```

Row {.tabset}
-----------------------------------------------------------------------

### Precipitation
```{r}
dygraphOutput ('precipGraph')
```

### Evapotranspiration
```{r}
dygraphOutput("evapGraph")
```

### Temperature
```{r}
# {.tabset data-width=400}
# fillRow(flex = c(NA, 1),
# tabsetPanel(type = "tabs",
#             tabPanel("Precipitation", dygraphOutput ('precipGraph')),
#             tabPanel("Evaporation", dygraphOutput("evapGraph")),
#             tabPanel("Monthly flows", highchartOutput("catchAggGraph")),
#             tabPanel("Temperature" , highchartOutput("tempGraph")),
#             tabPanel("Water use", highchartOutput("waterUseGraph")))

plotlyOutput("tempGraph")
```

### Discharge
```{r}
plotlyOutput("catchAggGraph")
```

### Water use 
```{r}
plotlyOutput("waterUseGraph")
```

```{r context = "server"}

# check if change is triggered by user or by reactivity, dygraph won't update date range input is changed because range selector is used to change dygraph

  r <- reactiveValues(
    change_datewindow = 0,
    change_dateTS = 0,
    change_datewindow_auto = 0,
    change_dateTS_auto = 0,
    dateTS = c(start = "1993-01-01",
               end = "2018-12-31")
  )

 # dygraph updates if user interacts with range slider 
  observeEvent(input$catchTS_date_window, {
    message(crayon::blue("observeEvent_input_catchTS_date_window"))
    r$change_datewindow <- r$change_datewindow + 1
    if (r$change_datewindow > r$change_datewindow_auto) {

      r$change_dateTS_auto <- r$change_dateTS_auto + 1
      r$change_datewindow_auto <- r$change_datewindow

    start <- as.Date(ymd_hms(input$catchTS_date_window[[1]]))
    stop  <- as.Date(ymd_hms(input$catchTS_date_window[[2]]))
   updateDateRangeInput(session = session,
                       inputId = "dateTS",
                       start = start,end = stop
                       )
      
    } else {
      if (r$change_datewindow >= 10) {
        r$change_datewindow_auto <- r$change_datewindow <- 0
      }
    }
  })

  # dygraph updates if date range is inputted
  observeEvent(input$dateTS, {
    message("observeEvent_input_dateTS")
    r$change_dateTS <- r$change_dateTS + 1
    if (r$change_dateTS > r$change_dateTS_auto) {
      message("event input_year update")

      r$change_datewindow_auto <- r$change_datewindow_auto + 1
      r$change_dateTS_auto <- r$change_dateTS

      r$dateTS <- input$dateTS

    } else {
      if (r$change_dateTS >= 10) {
        r$change_dateTS_auto <- r$change_dateTS <- 0
      }
    }
  })
```
  
```{r context = "server"}

# Time series data/plot, reactive to input of date button
catchTSplot <- eventReactive(input$dateButton, {
    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    dygraph(ts)  %>%
          dyHighlight(highlightCircleSize = 3.5,
                highlightSeriesBackgroundAlpha = .4) %>%
          dyOptions(colors = c("darkcyan"),
              fillGraph = TRUE) %>%
          dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
                                         as.character(r$dateTS[2] + 1)))
        #   dyLimit(as.numeric(season[1, 4]), color = "red") %>% 
    #   dyLimit(as.numeric(season[2, 4]), color = "red") %>% 
    # dyLimit(as.numeric(season[3, 4]), color = "red")

  })

# Render time series after action button is clicked 
output$catchTS <- renderDygraph({
        catchTSplot()
      })
```

```{r context = "server"}
# year-month aggregated flow data/plot, reactive to input of date button
aggPlot <- eventReactive(input$dateButton, {
        nwm <-  readNWMdata(comid = comid)
        agg <- nwmHistoric::aggregate_ym(nwm)

        plot_ly(agg, x = ~ym, y = ~flow_cms, type = 'bar',  
                textposition = 'auto',
                marker = list(color = 'rgb(158,202,225)',
                           line = list(color = 'rgb(8,48,107)', width = 1.5))) %>% 
               layout(title = 'Monthly flow totals',
                 xaxis = list(title = "",tickfont = list(size = 14, 
                        color = 'rgb(107, 107, 107)')),
                 yaxis = list(title = 'Flow rate (cubic m/s)',
                   titlefont = list(size = 16,color = 'rgb(107, 107, 107)'),
                   tickfont = list(size = 14,color = 'rgb(107, 107, 107)'))) %>% 
          config(displayModeBar = FALSE)
          # hchart(agg, type = "column", hcaes(x = ym, y = flow_cms)) %>%
      #   hc_colors(c("red", "green", "blue", "grey", "orange")) %>% 
      #   hc_size(height = 450)
})

# Render monthly flow totals plot after action button is clicked 
output$catchAggGraph <- renderPlotly({
          aggPlot()
        })


# county water use data/plot, reactive to input of date button
countyData <- eventReactive(input$dateButton, {

    nldi <- findNLDI(comid = comid) %>%
      st_centroid()
    conus <- USAboundaries::us_counties() %>%
      select(name, state_name)
    tmp1 <- st_intersection(nldi, conus) %>%
      st_drop_geometry() %>%
      slice(n =1)
    df = water_use_data(tmp1$state_name, tmp1$name)
    
    gg = ggplot(df, aes(x = year, y = withdrawals)) +
            geom_col(aes(fill = sector), position = position_dodge(4.1), width = 4) +
            scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                       expand = c(0, 0),
                       limits = c(0, NA)) +
            theme_classic() +
            labs(x = '',
                 y = "Withdrawals  (Mgal/day)",
                 fill = "")

        ggplotly(gg) %>%
            config(displayModeBar = FALSE)

    # plot_ly(df, x = ~year, y = ~Public, type = 'bar') %>%
    #             # textposition = 'auto',
    #             # marker = list(color = 'blue', width = 1.5)) %>%
    #       add_trace(df, x = ~year,
    #                 y = ~Irrigation,
    #                 type = 'bar',
    #                 name = "Irrigation",
    #                 marker = list(color = 'green',
    #                             width = 2)) %>%
    #       add_trace(df, x = ~year,
    #                 y = ~Industrial,
    #                 type = 'bar',
    #                 name = "Industrial",
    #                 marker = list(color = 'rgba(219, 64, 82, 0.7)',
    #                           line = list(color = 'rgba(219, 64, 82, 1.0)'))) %>%
    #       add_trace(df, x = ~year,
    #                 y = ~Thermoelectric,
    #                 type = 'bar',
    #                 name = "Thermoelectric",
    #                 marker = list(color = 'orange',
    #                             width = 2)) %>%
    #       add_trace(df, x = ~year,
    #                 y = ~Mining,
    #                 type = 'bar',
    #                 name = "Mining",
    #                 marker = list(color = 'grey',
    #                             width = 2)) %>%
    #         layout(title = 'Sector water use',
    #              # xaxis = list(title = "",
    #              #   tickfont = list(size = 14,color = 'rgb(107, 107, 107)')),
    #              # yaxis = list(title = 'Degrees (Celsius) ',
    #              #   titlefont = list(size = 16, color = 'rgb(107, 107, 107)'),
    #              #   tickfont = list(size = 14,color = 'rgb(107, 107, 107)')),
    #              # legend = list(x = 0, y = 1, bgcolor = 'rgba(255, 255, 255, 0)', bordercolor = 'rgba(255, 255, 255, 0)'),
    #              barmode = 'group',
    #              bargap = 0.2,
    #              bargroupgap = 0.15) %>%
    #         config(displayModeBar = FALSE)
    # hchart(df, type = "column", hcaes(x = YEAR, y = WITHDRAWALS, group = "Sector")) %>%
    #   hc_colors(c("red", "green", "grey", "blue", "orange")) %>%
    #   hc_size(height = 450)
  })

# Render water use plot after action button is clicked
output$waterUseGraph <- renderPlotly({
        countyData()
      })
```

```{r context = "server"}
# precip & evapotran data/plot, reactive to input of date button
precipData <- eventReactive(input$dateButton, {
  
    nldi <- findNLDI(comid = comid) %>% 
      st_centroid()
    precip <- climateR::getTerraClim(AOI = nldi, param = "prcp",
                                startDate = "1993-01-01",
                                endDate = "2015-01-01")

    precip$date <- paste0(precip$date, "-01")
    precip$date <- as.Date(precip$date)
    rownames(precip) <- precip$date
    precip <- select(precip, PPT = prcp)

    dygraph(data = precip,
            main = "PRECIPITATION",
            ylab = "Water volume (mm)") %>% 
      dyHighlight(highlightCircleSize = 4,
                highlightSeriesBackgroundAlpha = .4) %>%
          dyOptions(colors = c("navy"),
              fillGraph = TRUE)
      # dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
      #                                    as.character(r$dateTS[2] + 1)))
    # highchart() %>%
    #   hc_yAxis_multiples(list(title = list(text = "Accumulated Precipitation (mm)"),min=0, max = max(terra$prcp),
    #             showFirstLabel = TRUE, showLastLabel = TRUE, opposite = FALSE),
    #             list(title = list(text = "Actual Evapotranspiration (mm)"), showLastLabel=FALSE,opposite = TRUE)) %>%
    #   hc_add_series(terra, type = "column", hcaes(x = date, y = prcp), yAxis = 1 ) %>%
    #   hc_add_series(terra, type = "line", hcaes(x = date, y = aet), yAxis = 0) %>%
    #   hc_colors(c("darkcyan", "darkred")) %>% 
    #   hc_size(height = 450)
    })

# Render precip/evapo plot after action button is clicked 
output$precipGraph <- renderDygraph({
        precipData()
      })
```

```{r context = "server"}
# precip & evapotran data/plot, reactive to input of date button
evapData <- eventReactive(input$dateButton, {
  
    nldi <- findNLDI(comid = comid) %>% 
      st_centroid()
    evap <- climateR::getTerraClim(AOI = nldi, param = "aet",
                                startDate = "1993-01-01",
                                endDate = "2015-01-01")

    evap$date <- paste0(evap$date, "-01")
    evap$date <- as.Date(evap$date)
    evap <- evap %>% rename(AET = aet)
    rownames(evap) <- evap$date
    
    dygraph(data = select(evap,AET),
            main = "ACTUAL EVAPOTRANSPIRATION",
            ylab = "Water volume (mm)") %>% 
      dyHighlight(highlightCircleSize = 4,
                highlightSeriesBackgroundAlpha = .4) %>%
          dyOptions(colors = c("darkred"),
              fillGraph = TRUE)
      # dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
      #                                    as.character(r$dateTS[2] + 1)))
    
    # highchart() %>%
    #   hc_yAxis_multiples(list(title = list(text = "Accumulated Precipitation (mm)"),
    #                         min=0,
    #                         max = max(terra$prcp),
    #                         showFirstLabel = TRUE,
    #                         showLastLabel = TRUE,
    #                         opposite = FALSE),
    #                      list(title = list(text = "Actual Evapotranspiration (mm)"),
    #                         showLastLabel=FALSE,
    #                         opposite = TRUE)) %>%
    #   hc_add_series(terra, type = "column",
    #                 hcaes(x = date, y = prcp), yAxis = 1 ) %>%
    #   hc_add_series(terra, type = "line",
    #                 hcaes(x = date, y = aet), yAxis = 0) %>%
    #   hc_colors(c("darkcyan", "darkred")) %>% 
    #   hc_size(height = 450)
    })

# Render precip/evapo plot after action button is clicked 
output$evapGraph <- renderDygraph({
        evapData()
      })
```

```{r context = "server"}
# monthly mean Min and Max temps data/plot, reactive to input of date button
tempData <- eventReactive(input$dateButton, {
  
    nldi <- findNLDI(comid = comid) %>% 
      st_centroid()
    temp <- climateR::getTerraClim(AOI = nldi, param = c("tmax", "tmin"),
                       startDate = "1993-01-01",
                       endDate = "2014-12-31")

    temp <- temp %>%
      mutate(date = parse_date_time(temp$date, "ym")) %>%
      mutate(month = months(date), year = year(date)) %>%
      group_by(month) %>%
      mutate(meanMax = mean(tmax), meanMin = mean(tmin)) 
    
    temp$meanMax <- round(temp$meanMax, 2)
    temp$meanMin <- round(temp$meanMin, 2)
    
    temp <- temp %>% 
      mutate(mon_num = month(date)) %>% 
      group_by(month) %>% 
      arrange(date) %>% 
      slice(n = 12) %>% 
      ungroup() %>% 
      arrange(date)
    temp$month <- factor(temp$month, levels = c("January", "February", "March", 
                                                  "April", "May", "June","July", "August", 
                                                  "September", "October","November", "December" ))
    
    plot_ly(temp, x = ~month, y = ~meanMax, type = 'bar',  
                  textposition = 'auto',
                  name = "Max",
                  marker = list(color = 'rgba(219, 64, 82, 0.7)',
                              line = list(color = 'rgba(219, 64, 82, 1.0)',
                              width = 2))) %>% 
            add_trace(temp, x = ~month,
                    y = ~meanMin,
                    type = 'bar',
                    name = "Min",
                    marker = list(color = 'rgba(55, 128, 191, 0.7)',
                                line = list(color = 'rgba(55, 128, 191, 0.7)',
                                width = 2))) %>% 
            layout(title = 'Monthly mean temperature',
                 xaxis = list(title = "",
                   tickfont = list(size = 14,color = 'rgb(107, 107, 107)')),
                 yaxis = list(title = 'Temperature (°C) ',
                   titlefont = list(size = 16, color = 'rgb(107, 107, 107)'),
                   tickfont = list(size = 14,color = 'rgb(107, 107, 107)')),
                 legend = list(x = 0, y = 1, bgcolor = 'rgba(255, 255, 255, 0)', bordercolor = 'rgba(255, 255, 255, 0)'),
                 barmode = 'group',
                 bargap = 0.2, 
                 bargroupgap = 0.15) %>% 
            config(displayModeBar = FALSE)
    
    # highchart() %>%
    #   hc_add_series(temp, type = "column", hcaes(x = month, y = meanMax)) %>%
    #   hc_add_series(temp, type = "column", hcaes(x = month, y = meanMin)) %>%
    #   hc_colors(c("darkcyan", "darkred")) %>% 
    #   hc_size(height = 450)
    })

# Render mean temp plot after action button is clicked 
output$tempGraph <- renderPlotly({
        tempData()
      })

summaryData <- eventReactive(input$dateButton, {
      make_table3(comid)
    })
    
output$summaryTable <- renderDT({
          summaryData()
      })

```



























