---
title: "NWM"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://ufokn.com/", align: right }
    theme: flatly
    orientation: row
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinycustomloader)

library(dataRetrieval)
library(nhdplusTools)
library(nwmHistoric)
library(tidycensus)

library(lubridate)

library(leaflet)
library(sf)
library(ggplot2)
library(dplyr)
library(dygraphs)
library(DT)
library(formattable)


source('../nwm_shiny/helper.R')
```

```{r context="server"}
#Initialize Maps 
output$catchMap     <- renderLeaflet({ basemap() })
output$catchMap_2     <- renderLeaflet({ second_map() })
# output$countyMap <- renderLeaflet({ pop_map(pop) })

# comid <<- reactiveValues(comid = NULL)

comid <<- reactive({
  comid <-  input$catchMap_click
})

nwm <- reactiveValues()
```



NWM {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}
dateRangeInput("dateTS", label = "Date Range Input",
               start = "1993-01-01",
               end = "2018-12-31",
               format = "yyyy mm dd",
               weekstart = 1)
verbatimTextOutput("dateTSText")
verbatimTextOutput("dateTSText2")
htmlOutput("areaTable")
```

### **Submit**
```{r}
shiny::actionButton("dateButton", label = "Enter", icon("search"))
```

```{r context = "server"}
# observeEvent(input$catchTS_date_window, {
#   start <- as.Date(ymd_hms(input$catchTS_date_window[[1]]))
#   stop  <- as.Date(ymd_hms(input$catchTS_date_window[[2]]))
#   updateDateRangeInput(session = session,
#                        inputId = "dateTS",
#                        start = start,end = stop
#                        )
# })

# update_range <- eventReactive(input$dateButton, {
#       range <- paste(input$dateTS[1], input$dateTS[2], sep = "/")
#       return(ts[range])
#     })

# observeEvent(input$dateButton, {
#   
#     nwm <- readNWMdata(comid = comid)
#     ts = xts::xts(as.data.frame(nwm <- nwm$flow_cms), order.by = nwm <- nwm$dateTime, tz= 'UTC')
#       
# 
#     
#     
#     output$catchTS <- renderDygraph({
# 
#       dygraph(update_range)  %>%
#         dyHighlight(highlightCircleSize = 2,
#                 highlightSeriesBackgroundAlpha = .3) %>%
#         dyOptions(colors = c("darkcyan"),
#               fillGraph = TRUE) %>%
#         dyRangeSelector(dateWindow = c(as.character(input$dateTS[1]), as.character(input$dateTS[2])))
#     })
#   
# })
```

Row 
-----------------------------------------------------------------------
### 
```{r}
valueBoxOutput("comidBox")
```

Row 
-----------------------------------------------------------------------
### Draw
```{r}
leafletOutput("catchMap")
```

```{r context = "server"}

#### TEST POINT ####
# lat = 35.6643
# lng = -96.91935
# pt <- data.frame(lat, lng)
# pt <- sf::st_as_sf(pt,
#                 coords = c("lng", "lat"),
#                 crs = 4326)
# nldi <- findNLDI(location = pt)
#
#####################


# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + info panel
  observeEvent(input$catchMap_click, {
   if(!is.null(input$catchMap_click)) {
    click <<- input$catchMap_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid = nldi$comid
    
    print(comid)
    print("map1_click")
    #
    # catch_df <- get_nhdplus(comid = comid, realization = "catchment")
    
    bb <- st_bbox(nldi) # current bounding box
    
    # bounding box range
    xrange <- bb$xmax - bb$xmin # range of x values
    yrange <- bb$ymax - bb$ymin # range of y values
    
    # expand bb by 60% 
    bb[1] <- bb[1] - (0.6 * xrange) # xmin - left
    bb[3] <- bb[3] + (0.6 * xrange) # xmax - right
    bb[2] <- bb[2] - (0.6 * yrange) # ymin - bottom
    bb[4] <- bb[4] + (0.6 * yrange) # ymax - top
    
    # make bb a sfc
    bb <- bb %>%  # take the bounding box ...
        st_as_sfc() 
    catch_df <- get_nhdplus(AOI = bb, realization = "catchment")
    catch_df2 <- catch_df %>% 
      filter(featureid == comid)
    
    output$comidBox <- renderValueBox({
    valueBox(value = paste("COMID: ", comid),
      icon = "fa-id-badge",
      color = "primary") })
    
    output$comidBox2 <- renderValueBox({
    valueBox(value = paste("COMID: ", comid),
      icon = "fa-id-badge",
      color = "primary") })

    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt,
                 layerId = ~comid,) %>% 
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
      # zoom_to_catch(catch_df, comid)
    leafletProxy("catchMap_2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
    
    leafletProxy("catchMap_3") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt) %>% 
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
  
    output$areaTable <- renderText ({ make_table2(comid) })
    output$catchDT <- renderDataTable({ make_table(comid) })
   } 
})

# click on map 2 will render polygon, point on map 1 and 3
observeEvent(input$catchMap_2_click, {
   if(!is.null(input$catchMap_2_click)) {
    click <<- input$catchMap_2_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid = nldi$comid
    
    print(comid)
    print("map2_click")
    #
    # catch_df <- get_nhdplus(comid = comid, realization = "catchment")
    
    bb <- st_bbox(nldi) # current bounding box
    
    # bounding box range
    xrange <- bb$xmax - bb$xmin # range of x values
    yrange <- bb$ymax - bb$ymin # range of y values
    
    # expand bb by 60% 
    bb[1] <- bb[1] - (0.6 * xrange) # xmin - left
    bb[3] <- bb[3] + (0.6 * xrange) # xmax - right
    bb[2] <- bb[2] - (0.6 * yrange) # ymin - bottom
    bb[4] <- bb[4] + (0.6 * yrange) # ymax - top
    
    # make bb a sfc
    bb <- bb %>%  # take the bounding box ...
        st_as_sfc() 
    catch_df <- get_nhdplus(AOI = bb, realization = "catchment")
    catch_df2 <- catch_df %>% 
      filter(featureid == comid)
    
    output$comidBox <- renderValueBox({
    valueBox(value = paste("COMID: ", comid),
      icon = "fa-id-badge",
      color = "primary") })
    
    output$comidBox2 <- renderValueBox({
    valueBox(value = paste("COMID: ", comid),
      icon = "fa-id-badge",
      color = "primary") })

    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt,
                 layerId = ~comid,) %>% 
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
      # zoom_to_catch(catch_df, comid)
    leafletProxy("catchMap_2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
    
    leafletProxy("catchMap_3") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt) %>% 
      addPolygons( data = catch_df2,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   col = 'yellow')
  
    output$areaTable <- renderText ({ make_table2(comid) })
    output$catchDT <- renderDataTable({ make_table(comid) })
   } 
})

# catchMap and catchMap_2 are linked while zooming
  observe({ # Observer to respond to zoom / pan of map1 and apply to map2
    coords <- input$catchMap_center
    zoom <- input$catchMap_zoom
    print(coords)
    print(zoom)
    if (!is.null(coords)) {
      leafletProxy("catchMap_2") %>%
        setView(lat = coords$lat, lng = coords$lng, zoom = zoom)
    }
})
```

Row 
-----------------------------------------------------------------------
### Time series
```{r}
dygraphOutput("catchTS")
```

### Map 2
```{r}
leafletOutput("catchMap_2")
```

```{r context = "server"}
# testing reactivity with date range input & button
dateTSText <- eventReactive(input$dateButton, {
  paste0("'", as.character(input$dateTS[1]), "/", as.character(input$dateTS[2]), "'")
 
  })
  
  output$dateTSText <- renderText({
   dateTSText()
  })
  
dateTSText2 <- eventReactive(input$dateButton, {
      range <- paste(input$dateTS[1], input$dateTS[2], sep = "/")
      print(range)
    })

  output$dateTSText2 <- renderText({
   dateTSText2()
  })
```


```{r context = "server"}

# check if change is triggered by user or by reactivity, dygraph won't update date range input is changed because range selector is used to change dygraph

  r <- reactiveValues(
    change_datewindow = 0,
    change_dateTS = 0,
    change_datewindow_auto = 0,
    change_dateTS_auto = 0,
    dateTS = c(start = "1993-01-01",
               end = "2018-12-31")
  )

 # dygraph updates if user interacts with range slider 
  observeEvent(input$catchTS_date_window, {
    message(crayon::blue("observeEvent_input_catchTS_date_window"))
    r$change_datewindow <- r$change_datewindow + 1
    if (r$change_datewindow > r$change_datewindow_auto) {

      r$change_dateTS_auto <- r$change_dateTS_auto + 1
      r$change_datewindow_auto <- r$change_datewindow

    start <- as.Date(ymd_hms(input$catchTS_date_window[[1]]))
    stop  <- as.Date(ymd_hms(input$catchTS_date_window[[2]]))
   updateDateRangeInput(session = session,
                       inputId = "dateTS",
                       start = start,end = stop
                       )
      
    } else {
      if (r$change_datewindow >= 10) {
        r$change_datewindow_auto <- r$change_datewindow <- 0
      }
    }
  })

  # dygraph updates if date range is inputted
  observeEvent(input$dateTS, {
    message("observeEvent_input_dateTS")
    r$change_dateTS <- r$change_dateTS + 1
    if (r$change_dateTS > r$change_dateTS_auto) {
      message("event input_year update")

      r$change_datewindow_auto <- r$change_datewindow_auto + 1
      r$change_dateTS_auto <- r$change_dateTS

      r$dateTS <- input$dateTS

    } else {
      if (r$change_dateTS >= 10) {
        r$change_dateTS_auto <- r$change_dateTS <- 0
      }
    }
  })
  observeEvent(input$catchMap_click, {
    
    click <<- input$catchMap_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid <- nldi$comid
    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    
      output$catchTS <- renderDygraph({
        print("date change button")
        dygraph(ts)  %>%
          dyHighlight(highlightCircleSize = 2,
                highlightSeriesBackgroundAlpha = .3) %>%
          dyOptions(colors = c("darkcyan"),
              fillGraph = TRUE) %>%
          dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
                                         as.character(r$dateTS[2] + 1)))
      })
})
  
    observeEvent(input$catchMap_2_click, {
    
    click <<- input$catchMap_2_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
    nldi <- findNLDI(location = pt)
    comid <- nldi$comid
    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    
      output$catchTS <- renderDygraph({
        print("date change button")
        dygraph(ts)  %>%
          dyHighlight(highlightCircleSize = 2,
                highlightSeriesBackgroundAlpha = .3) %>%
          dyOptions(colors = c("darkcyan"),
              fillGraph = TRUE) %>%
          dyRangeSelector(dateWindow = c(as.character(r$dateTS[1] + 1),
                                         as.character(r$dateTS[2] + 1)))
      })
})
```

Data Table {data-orientation=columns data-icon="fa-filter"}
=====================================

Inputs {.sidebar}
-------------------------------------
### Model Filters
```{r}
# sliderInput("hour_table", dates$nwm_date_range$local_tz[1], value = 0, min = 0, max = 23, step = 1)
shiny::actionButton("button_table", label = "Submit Query", icon("search"))
```


Column {data-width=600}
-----------------------------------------------------------------------
### 
```{r}
valueBoxOutput("comidBox2")
```

### Data table
```{r}
# `r renderText({ values$display })`
dataTableOutput("catchDT")
```

### Population density
```{r}
leafletOutput("countyMap")
```

```{r context = "server"}
#   observeEvent(input$catchMap_3_click , {
#     click <<- input$catchMap_3_click %>% 
#             data.frame() %>% 
#             dplyr::select(lat,lng)
#     
#           print(click)
#     pt <- sf::st_as_sf(click, 
#                         coords = c("lng", "lat"), 
#                         crs = 4326)
#   
#   
#     nldi <- findNLDI(comid = comid)
#    
#     nldi <- st_transform(nldi, 5070)
# 
#     buff <- st_buffer(nldi, 50000) %>% 
#           st_transform(4326)
#     overlap_counties <- st_filter(pop, buff, .predicate = st_intersects)
#     
#     output$countyMap <- renderLeaflet({ pop_map(overlap_counties) })
# })
```


Column {data-width=800}
-----------------------------------------------------------------------
### Map 3
```{r}
leafletOutput("catchMap_3") 
```

```{r context = "server"}
# load polygons when map 3 is clicked
output$catchMap_3 <- renderLeaflet({ basemap() })
  observeEvent(input$catchMap_3_click, {
    # pt <<- NULL
    click <<- input$catchMap_3_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    nldi <- findNLDI(comid = 101)
    comid = nldi$comid
    print(comid)
    
    # output$catchTS <- renderDygraph({ make_ts(pt) })

    output$comidBox2 <- renderValueBox({
      valueBox(value = paste("COMID: ", comid),
        icon = "fa-water",
        color = "success") })
    output$comidBox <- renderValueBox({
      valueBox(value = paste("COMID: ", comid),
        icon = "fa-water",
        color = "success") })
    
    print("map3_click1")
    # output$areaTable <- renderText({ make_table2(comid) })
    # # 
    # catch_df <- get_nhdplus(comid = comid, realization = "catchment")
    
    bb <- st_bbox(nldi) # current bounding box
    
    # bounding box range
    xrange <- bb$xmax - bb$xmin # range of x values
    yrange <- bb$ymax - bb$ymin # range of y values
    
    # expand bb by 60% 
    bb[1] <- bb[1] - (0.6 * xrange) # xmin - left
    bb[3] <- bb[3] + (0.6 * xrange) # xmax - right
    bb[2] <- bb[2] - (0.6 * yrange) # ymin - bottom
    bb[4] <- bb[4] + (0.6 * yrange) # ymax - top

    # make bb a sfc
    bb <- bb %>%  # take the bounding box ...
        st_as_sfc() 
    
    catch_df <- get_nhdplus(AOI = bb, realization = "catchment")
    catch_df2 <- catch_df %>% 
      filter(featureid == comid)
  
    leafletProxy("catchMap_3") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt) %>%
      addPolygons( data = catch_df2,
                   layerId = ~comid,
                   col = 'red') %>% 
      addPolygons( data = catch_df,
                   layerId = ~comid,
                   col = 'blue')
    leafletProxy("catchMap") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt) %>%
      addPolygons( data = catch_df,
                   layerId = ~comid,
                   col = 'blue')
    leafletProxy("catchMap_2") %>%
      clearMarkers() %>%
      clearShapes() %>%
      addMarkers(data = pt,
                 layerId = ~comid) %>%
      addPolygons( data = catch_df,
                   col = 'blue')
})

```

```{r context = "server"}

# Clicking map 3, outputs data table on page 2 + Timeseries on page 1
  observeEvent(input$catchMap_3_click, {
    # pt <<- NULL
    click <<- input$catchMap_3_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)

    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)


    nldi <- findNLDI(location = pt)

    comid = nldi$comid
    print(comid)

    output$catchDT <- renderDataTable({ make_table(comid) })

    nwm <- readNWMdata(comid = comid)
    ts = xts::xts(as.data.frame(nwm$flow_cms), order.by =nwm$dateTime, tz= 'UTC')
    output$catchTS      <- renderDygraph( {make_ts4(ts) })
})
```
























